name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.12'
    
    - name: Install dependencies
      run: pip install -r requirements.txt pytest
    
    - name: Run tests
      run: pytest -v

    - name: Debug /tmp directory
      run: |
        echo "Runner OS: $RUNNER_OS"
        if [ "$RUNNER_OS" == "Windows" ]; then
          ls "${{ runner.temp }}"
        else
          ls -la /tmp
        fi
    
    # Posible guardado de artifacts

    # - name: Build Docker image
    #   run: docker build --no-cache -t ml-api:${{ github.sha }} .

    # - name: Save Docker image
    #   run: |
    #       docker save ml-api:${{ github.sha }} -o /tmp/docker-image.tar
    #       ls -lh /tmp/docker-image.tar
    
    # - name: Upload Docker image
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: docker-image
    #     path: /tmp/docker-image.tar
    #     if-no-files-found: error

  deploy:
    needs: test-and-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # - name: Download Docker image
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: docker-image
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build Docker image
      run: docker build --no-cache -t ml-api:${{ github.sha }} .
    
    - name: Push to Registry
      run: |
        docker tag ml-api:${{ github.sha }} skinwalkerirl/ml-api:${{ github.sha }}
        docker push skinwalkerirl/ml-api:${{ github.sha }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MLOpsJRB'
        slot-name: 'production'
        package: .  
        clean: true  # Cleans target directory before deployment
        restart: true  # Restarts app after deployment